---
title: projectCASA_EDA
author: ~
date: '2020-06-06'
slug: projectcasa-eda
categories: []
tags: []
---
#### 0. 들어가며
- 이 게시글은 서울 아파트 실거래가 예측 시스템을 구축하는 프로젝트에서 EDA파트를 담고 있다.

#### 1. EDA에 필요한 라이브러리
```python
import pandas as pd
import json
import psycopg2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')
```

#### 2. 데이터프레임 불러오기 
```python
def call_df(table_name):
    with open('config.json', 'r') as f:
        config = json.load(f)
        
    conn = psycopg2.connect(user = config['USER'],
                              password = config['PASSWORD'],
                              host = config['HOST'],
                              port = config['PORT'],
                              database = config['DATABASE'])
    
    sql = f'SELECT * FROM {table_name}'
    df = pd.read_sql_query(sql, conn)
    conn.close()
    return df
```

```python
district = call_df('crawling_db.district_table')
apartment = call_df('crawling_db.apartment_table').drop(columns='table_id')
school = call_df('crawling_db.school_table').drop(columns='table_id')
price = call_df('crawling_db.price_table')
subway = call_df('crawling_db.subway_table').drop(columns='table_id')
```

```python
df = (price.merge(apartment, how='left', on='apartment_id').
      merge(district, how='left', on='district_id').
      merge(school, how='left', on='apartment_id').
      merge(subway, how='left', on='apartment_id'))
```
#### 3. 데이터 분석을 위한 기본적인 데이터 전처리
##### 1) 분석에 용이하도록 Object 변수 변환
```python
# school_Students를 숫자형 변수로 바꿔준다
df['school_students'] = pd.to_numeric(df['school_students'])
```

```python
# area에서 숫자가 아닌 부분을 제거해준다 
import re
df['area'] = df['area'].apply(lambda x: int(re.split('\D',x)[0]))
```

```python
#'school_addr_town'에서 ~길의 내용을 제거하고 ~로까지 확인한다 
import re
df['school_addr_town'] = df['school_addr_town'].apply(lambda x: re.split('\d',x)[0])

# chool_addr_town'에서 '로' 를 '동'으로 바꿔준다 
df['school_addr_town'] = df['school_addr_town'].apply(lambda x: x.replace('로','동'))
```

##### 2)null값 확인 
```python
df.isnull().any()
```
- 학교 학생수에 null값 발생 
```python
df = df.fillna(0)
```

##### 3)이상치 제거 
- 실거래가를 자치구별로 나타내고 이상치 제거
```python
figure,ax1 = plt.subplots()
figure.set_size_inches(18,5)

sns.boxplot(data=df,y='amount',x='district_id')
```
- 이상치는 동일 면적의 해당 아파트 거래가 한번인 경우 제거하지 않았다
- 해당 아파트에 대한 거래 정보가 없어지기 때문
```python
df.drop(df[df['district_id']==2].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
df.drop(df[df['district_id']==6].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
df.drop(df[df['district_id']==12].sort_values(by='amount',ascending=False).head(5).index,inplace=True)
#df.drop(df[df['district_id']==13].sort_values(by='amount',ascending=False).head(2).index,inplace=True) 거래가 총 2번 이루어져서 제거 안함
df.drop(df[df['district_id']==14].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
df.drop(df[df['district_id']==16].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
df.drop(df[df['district_id']==18].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
df.drop(df[df['district_id']==19].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
df.drop(df[df['district_id']==22].sort_values(by='amount',ascending=False).head(3).index,inplace=True)#신호아파트 면적97인 아파트의 경우 한번 거래가 이루어져 제거 안함
df.drop(df[df['district_id']==24].sort_values(by='amount',ascending=False).head(1).index,inplace=True)
```

```python
#이상치를 제거한 boxplot
figure,ax1 = plt.subplots()
figure.set_size_inches(18,5)

sns.boxplot(data=df,y='amount',x='district_id')
```

#### 4. Feature selecting & 데이터 분석 
- 클러스터링에 사용할 변수를 선택하기 위해 각 변수와 amount의 상관관계 파악에 중점을 두어 분석
- 데이터의 분포와 값을 살펴보면서 데이터에 대한 이해 증진
- 변수는 크게 5가지로 나누어 살펴볼 것
```python
# 시계열에만 사용될 변수를 제거하고 heatmap을 사용해 상관관계를 살펴보았다
temp = df.drop(['apartment_id','area','year','month'],axis=1)
figure,ax1 = plt.subplots()
figure.set_size_inches(10,10)

sns.heatmap(temp.corr(),annot=True,cmap='YlGnBu')
```
- 수치상으로 'apartment_parking' 'school_students' 'st_dist'변수가 상대적으로 amount값과 높은 상관관계를 보인다
- 각 변수별로 자세히 알아보자

##### 1) 연도별 거래액 
```python
#2020년도의 경우 6월달까지의 거래액만 존재해서 제외
a = df[df['year']<2020]
figure,ax1 = plt.subplots()
figure.set_size_inches(18,6) 

sns.barplot(data=a,x="year",y="amount",ax=ax1)
```
- 2009년도부터 2013년까지의 실거래가가 감소하나, 2013년도부터 실거래가 증가

##### 2) 학교정보 
```python
df['school_name'].nunique()
```
###### school_id 
- 학교 id에 따른 2019년도 거래가를 구해서 분포를 살펴보았다 
```python
sample = df[df['school_students']>0]
sample = sample.groupby(['school_name','year'])['amount'].mean().reset_index()
sample_2019 = sample[sample['year']==2019]
sample_2019.head()
```

```python
figure,(ax1,ax2) = plt.subplots(nrows=1,ncols=2)
figure.set_size_inches(18,6) 

sns.scatterplot(sample_2019['school_name'],sample_2019['amount'],ax=ax1)
sns.distplot(sample_2019['amount'],ax=ax2,bins=100)
```
- 가격의 분포가 5억을 중심으로 정규분포에 근사하며, 학교에 따라 다양한 값을 가짐

###### 학교 주소 
```python
a = df['school_addr_district']==df['district_id']
a = pd.DataFrame(a)
sns.heatmap(a,cbar=False, cmap="YlGnBu")
```
- 'school_add_district'와'district_id' 값이 모두 동일하므로 제거한다

###### school_dist 
```python
df['school_dist'].max()
```
- 아파트에서 가장 가까운 학교까지의 거리는 최대 도보 29분
```python
figure,ax1 = plt.subplots()
figure.set_size_inches(12,6) 

sns.boxplot(x="school_dist",y="amount",data=df,color="m",ax=ax1)
```
- 아파트에서 학교까지의 거리에 따른 amount값이 큰 차이를 보이지 않는다. 특히 17분 이하의 경우에는 거의 동일한 box plot을 갖는다 -- 제거
- heatmap의 0.023 수치에서도 확인 가능

###### school_Students
```python
ind = df[df['school_name']=='서울가산초등학교'].index
temp = df.drop(ind)
# 서울가산초등학교의 경우 데이터에 따라 금천구 구로구에 모두 속한다고 표기되어 있음 제거해준다
```

```python
temp = temp.groupby('school_name').mean()[['school_students','amount']].dropna()
temp = pd.merge(temp,df[['district_name','school_name']],how='left',on='school_name').drop_duplicates().reset_index()
temp.head()
```

```python
sns.distplot(temp['school_students'],bins=100)
```

```python
# 학교 학생수가 2000명이 넘는 학교는 한군데로 제거하고 분석을한다 
temp = temp[temp['school_students']<2000]
```
- 자치구별 세대수와 학교 학생수의 비율을 구하고, 그 비율에 따른 amount값의 분포를 살펴보고자 한다
```python
# 각 자치구 별 세대수
population = pd.read_excel("population.xlsx")
population.drop(['※ 매년 말일자 통계 현황','Unnamed: 4'],axis=1,inplace=True)
population.drop([0,1,2],inplace=True)
population.rename(columns={'Unnamed: 1':'district_name','Unnamed: 2':'총인구수','Unnamed: 3':'세대수'},inplace=True)
population['district_name'] = population.district_name.str.split(' ').str[1]
population['세대수'] = population.세대수.str.replace(',', '').astype('int64')
population = population.drop('총인구수',axis=1)
population.head()
```

```python
df1 = pd.merge(temp,population,how='left',on='district_name')
df1['ratio'] = 0.0
for ind in df1.index:
  a = float(df1['세대수'][ind])
  b = float(df1['school_students'][ind])
  df1['ratio'][ind] = b/a
```

```python
sns.distplot(df1['ratio'],bins=100)
```
- ratio는 0.00038과 0.015사이
- ratio가 0.015이상인 학교는 한 사례로 제거한다

```python
df1 = df1[df1['ratio']<0.015]
```

```python
figure,ax1 = plt.subplots()
figure.set_size_inches(6,6) 

sns.regplot(x="ratio",y="amount",data=df1,color="m",ax=ax1)
```
- ratio가 클수록 아파트의 실거래가가 높아진다
- ratio를 구간별로 나누어 실거래가와의 관계를 살펴본다
```python
factor = pd.cut(df1.ratio,5)
a = df1.amount.groupby(factor).mean()
a = pd.DataFrame(a)
a = a.reset_index()


figure,ax1 = plt.subplots()
figure.set_size_inches(18,5) 

sns.barplot(data=a,x="ratio",y="amount",ax=ax1)
```
- 자치구 세대수 인구 대비 학교 학생수의 비율이 커질수록, amount가 커지는 경향

##### 3) 세대당 주차대수 
```python
figure,ax1 = plt.subplots()
figure.set_size_inches(18,6) 
sns.distplot(df['apartment_parking'],ax=ax1,bins=60)
```
- 세대당 주차대수는 0~2대 사이에 주로 분포
```python
figure,ax1 = plt.subplots()
figure.set_size_inches(18,5) 

sns.barplot(data=df,x="apartment_parking",y="amount",ax=ax1)
```
- 세대당 주차대수의 값이 커질수록 amount의 값이 점진적으로 우상향하는 것을 확인할 수 있다

##### 4) 건설 
```python
df['apartment_builder'].nunique()
```
- 2520개의 건설사 존재

###### apartment_Builder 
- 건설사에 따른 2019년도의 거래가를 구해서 거래가의 분포를 살펴보았다
```python
sample = df.groupby(['apartment_builder','year'])['amount'].mean().reset_index()
sample_2019 = sample[sample['year']==2019]
sample_2019.head()
```
```python
figure,(ax1,ax2) = plt.subplots(nrows=1,ncols=2)
figure.set_size_inches(18,6) 

sns.scatterplot(sample_2019['apartment_builder'],sample_2019['amount'],ax=ax1)
sns.distplot(sample_2019['amount'],ax=ax2,bins=200)
```
- 건설사별 2019년 아파트 평균 가격을 구하였을 때, 10억 이하의 값으로 편중되어있다 > 제거한다

###### apartment_build_year
```python
figure,ax1 = plt.subplots()
figure.set_size_inches(18,5) 

sns.pointplot(data=df,x="apartment_build_year",y="amount",ax=ax1)
```
- 일의자리수를 제거하고 연도별 분석 
```python
df['apartment_build_year'] = df['apartment_build_year'].apply(lambda x : x - x%10)
a = df['apartment_build_year'].value_counts()
a = pd.DataFrame(a)
a.reset_index(inplace=True)
a.rename(columns={'index':'apartment_build_year','apartment_build_year':'count'},inplace=True)


figure,(ax1,ax2) = plt.subplots(nrows=1,ncols=2)
figure.set_size_inches(18,6) 

sns.barplot(data=df,x="apartment_build_year",y="amount",ax=ax1)
sns.barplot(data=a,x="apartment_build_year",y="count",ax=ax2)
```
- 1970, 2020년대에 지어진 아파트의 수가 적은거에 비해 amount의 평균이 높다
- 2000년대에 가장 많이 아파트가 지어졌지만, 그에 비해 amount의 평균이 낮음

##### 5) 지하철역 
```python
df['st_name'].nunique()
```
###### st_name
- 지하철역에 따른 2019년도의 거래가를 구해서 거래가의 분포를 살펴보았다
```python
sample = df.groupby(['st_name','year'])['amount'].mean().reset_index()
sample_2019 = sample[sample['year']==2019]
sample_2019.head()
```
```python
figure,(ax1,ax2) = plt.subplots(nrows=1,ncols=2)
figure.set_size_inches(18,6)

sns.scatterplot(sample_2019['st_name'],sample_2019['amount'],ax=ax1)
sns.distplot(sample_2019['amount'],ax=ax2,bins=100)
```
- 각 지하철역 근처 아파트의 2019년 거래가 평균을 살펴보았을 때, 가격의 분포가 역에 따라 다양한 값을 갖는다

###### st_volume 
```python
figure,(ax1,ax2) = plt.subplots(nrows=2,ncols=1)
figure.set_size_inches(18,10) 

sns.barplot(data=df,y='amount',x='st_volume',ax=ax1)
sns.pointplot(data=df,y='amount',x='year',hue='st_volume',ax=ax2)
```
- 환승역이 4개인 곳의 실거래가가 2014년도 이후부터 꾸준히 증가
- 환승역의 개수 별 거래액이 큰 차이를 보이지 않는다 > 제거

###### st_dist
```python
a = df.groupby('st_dist').mean()['amount']
a = pd.DataFrame(a).reset_index()

figure,ax1 = plt.subplots()
figure.set_size_inches(10,10) 

sns.regplot(x="st_dist",y="amount",data=a,color="m",ax=ax1)
```
- 가까운 역까지의 거리와 거래액은 음의 상관관계를 보인다
- 이번에는 거리를 구간별로 나눠서 살펴보자 
```python
factor = pd.cut(df.st_dist,7)
a = df.amount.groupby(factor).mean()
a = pd.DataFrame(a)
a = a.reset_index()

figure,ax1 = plt.subplots()
figure.set_size_inches(18,5) 

sns.barplot(data=a,x="st_dist",y="amount",ax=ax1)
```
- 거리가 0.0247 이하인 경우 지하철역에서 거리가 가까울수록 거래가가 비싸지만, 0.0247보다 큰 경우에는 양의 상관관계를 보인다
- 지하철역과 거리가 가장 먼 곳이 가장 높은 평균 거래가를 갖는다
```python
df[df['st_dist']>0.0296]['apartment_addr_town'].drop_duplicates()
```
- 지하철역과의 거리가 0.0296보다 큰 지역을 살펴보니, 평창동임을 확인할 수 있었다 > 자가용을 이용하는 동네

###### Feature selecting 
- 최종적으로 클러스터링에 'district_id' 'apartmnet_addr_town' 'apartment_build_year' 'apartment_parking' 'school_name' 'school_students' 'st_name' 'st_dist'변수를 사용하기로 결정했다