---
title: "data_Visualization"
author: "yoorim cho"
date: '2020-06-06'
slug: data-visualization
categories: []
tags: []
---
# 주제 
- 서울 자전거(따릉이)는누구나 편리하게 사용할 수 있는 무인 자전거 대여 시스템으로, 교통체증과 대기오염의문제를 해결하기 위해 마련되었다. 본인은 서울시 공공자전거 대여소별 반납 건수와 대여 건수를 비교하여 수요를 파악하고자 한다. 이는 해당 대여소의 자전거와 거치대 수의 확대 여부에 대한 의사결정에 도움이 될 것으로 판단된다.

# 데이터
서울 열린 데이터 광장 [https://data.seoul.go.kr/] 데이터를 사용하였다.

# 시각화 내용
**1. 각 대여소별 2018년6월의 대여 건수와 반납 건수 비교 (2019년자료가없어 최신 데이터를 사용하지 못하였다)**
서울 열린 데이터 광장에서 제공하고 있는 서울 자전거 관련 공공데이터를이용해 시각화를 진행하였다. 대여소별 대여 건수와 반납 건수를 비교하여, 반납 건수가 많은 지역은 파란색 대여 건수가 많은 지역은 빨간색으로 표시하였다. 원의 크기는 반납 건수와 대여 건수의 차이를 표준화하여절댓값이 클수록 크게 표시하였다.

**2.자전거의 수가 부족한 대여소**
서울특별시공공자전거 대여 이력을 통해 이용자가 자전거를 대여시 잔여 자전거 수가 2대 이하인 사건을 구하였다. 그리고 해당 사건이 빈 번하게 발생한 대여소 상위 10군데를위도와 경도를 통해 시각화하였다.

# 시각화 방법
- 파이썬 folium 시각화 패키지를 이용하여 지도에 시각화하였다


- 대여정보와, 이용자정보에 대한 데이터프레임을 가져온다 
```python
import pandas as pd
import folium
rental_info = pd.read_csv("./DATA/rental_info.csv",engine='python')
rental_info.head()
```

```r
library(readxl)
rental_office_info <- read_excel('./DATA/rentaloffice_info.xlsx')
rental_office_rental_info <- read_excel('./DATA/rentaloffice_rental_info.xlsx')
rental_office_info
rental_office_rental_info
```

- 2018.06월달 대여소별 대여건수와 반납건수를 구한다 
```python
rental_office_rental_info = rental_office_rental_info[rental_office_rental_info['대여일자']==201806]
rental_office_info = rental_office_info.drop(['대여소주소','기준시작일자'],axis=1)
rental_office_rental_info = rental_office_rental_info.drop(['대여일자','대여소명'],axis=1)
```

- 대여소 별 위도/경도 dataframe과 대여/반납건수 dataframe을 merge해준다 
```python
rental_office = pd.merge(rental_office_info,rental_office_rental_info,how='left',left_on='대여소ID',right_on='대여소번호')
rental_office = rental_office.dropna()
rental_office = rental_office.drop('대여소번호',axis=1)
rental_office.head()
```
- 반납건수가 더 많은 경우 0 대여건수가 더 많은 경우 1 동일한 값을 갖는 경우는 2를 출력한다. 
```python
def num(x):
    if x['대여건수'] < x['반납건수']:
         return 0
    if x['대여건수'] > x['반납건수']:
         return 1
    else: return 2
```
```python
def diff(x):
    if x['대여건수'] < x['반납건수']:
         return x['반납건수'] - x['대여건수']
    if x['대여건수'] > x['반납건수']:
         return x['대여건수'] - x['반납건수']
    else: return 1
```
```python
rental_office['compare_rental'] = rental_office.apply(lambda x: num(x),axis=1)
rental_office['difference'] = rental_office.apply(lambda x: diff(x),axis=1)=1
```
```python
for i in rental_office.index:
    a = (rental_office.loc[i,'difference'] - rental_office['difference'].mean())/rental_office['difference'].std()
    rental_office.loc[i,'difference'] = a
```
- compare_rental값에 따라 dataframe을 각각 구한다 
```python
df1 = rental_office[rental_office['compare_rental'] == 0][['대여소명','대여소ID','위도','경도','거치대수','difference']]
df2 = rental_office[rental_office['compare_rental'] == 1][['대여소명','대여소ID','위도','경도','거치대수','difference']]
df3 = rental_office[rental_office['compare_rental'] == 2][['대여소명','대여소ID','위도','경도','거치대수','difference']]
```
```python
for i in df1.index:
    a = (df1.loc[i,'difference'] - df1['difference'].mean())/df1['difference'].std()
    df1.loc[i,'difference'] = a
```
```python
for i in df2.index:
    a = (df2.loc[i,'difference'] - df2['difference'].mean())/df2['difference'].std()
    df2.loc[i,'difference'] = a
```

- 대여소별 대여 건수와 반납 건수를 비교하여, 반납 건수가 많은 지역은 파란색 대여 건수가 많은 지역은 빨간색으로 표시하였다. 원의 크기는 반납 건수와 대여 건수의 차이를 표준화하여절댓값이 클수록 크게 표시하였다
```python
for item in df1.index:
    lat = df1.loc[item,'위도']
    long = df1.loc[item,'경도']
    folium.CircleMarker([lat,long],
                       radius = df1.loc[item,'difference'],
                       popup = df1.loc[item,'대여소명'],
                       color = 'blue',
                       fill = True).add_to(map_osm)
```
```python
for item in df2.index:
    lat = df2.loc[item,'위도']
    long = df2.loc[item,'경도']
    folium.CircleMarker([lat,long],
                       radius = df2.loc[item,'difference'],
                       popup = df2.loc[item,'대여소명'],
                       color = 'red',
                       fill = True).add_to(map_osm)
```
```python
map_osm
```

- 서울특별시공공자전거 대여 이력을 통해 이용자가 자전거를 대여시 잔여 자전거 수가 2대 이하인 사건을 구한다
```python
a = rental_info[rental_info['대여거치대']<=2][['대여 대여소번호','대여거치대']]
a = a['대여 대여소번호'].value_counts()
a = pd.DataFrame(a)
a.reset_index(inplace=True)
a.rename(columns={'index':'대여소ID','대여 대여소번호':'횟수'},inplace=True)
a.head()
```
```python
df = pd.merge(a,long_lat,how='left',on='대여소ID')
df.dropna(inplace=True)
df = df.head(10)
df
```
```python
map_osm4 = folium.Map(location=[37.5502, 126.982],zoom_start=12)
for item in df.index:
    lat = df.loc[item,'위도']
    long = df.loc[item,'경도']
    folium.Marker([lat,long]).add_to(map_osm4)
map_osm4
```